export const INIT_FETCH_STATES = "INIT_FETCH_STATES"
export const FETCH_STATES_SUCCESS = "FETCH_STATES_SUCCESS"
export const FETCH_STATES_FAILED = "FETCH_STATES_FAILED"

export const INIT_ADD_STATES = "INIT_ADD_STATES"
export const ADD_STATES_SUCCESS = "ADD_STATES_SUCCESS"
export const ADD_STATES_FAILED = "ADD_STATES_FAILED"

export const INIT_UPDATE_STATES = "INIT_UPDATE_STATES"
export const UPDATE_STATES_SUCCESS = "UPDATE_STATES_SUCCESS"
export const UPDATE_STATES_FAILED = "UPDATE_STATES_FAILED"

export const INIT_DELETE_STATES = "INIT_DELETE_STATES"
export const DELETE_STATES_SUCCESS = "DELETE_STATES_SUCCESS"
export const DELETE_STATES_FAILED = "DELETE_STATES_FAILED"

export const INIT_SINGLE_STATES = "INIT_SINGLE_STATES"
export const SINGLE_STATES_SUCCESS = "SINGLE_STATES_SUCCESS"
export const SINGLE_STATES_FAILED = "SINGLE_STATES_FAILED"

