export const INIT_FETCH_CITIES = "INIT_FETCH_CITIES"
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS"
export const FETCH_CITIES_FAILED = "FETCH_CITIES_FAILED"

export const INIT_ADD_CITIES = "INIT_ADD_CITIES"
export const ADD_CITIES_SUCCESS = "ADD_CITIES_SUCCESS"
export const ADD_CITIES_FAILED = "ADD_CITIES_FAILED"

export const INIT_UPDATE_CITIES = "INIT_UPDATE_CITIES"
export const UPDATE_CITIES_SUCCESS = "UPDATE_CITIES_SUCCESS"
export const UPDATE_CITIES_FAILED = "UPDATE_CITIES_FAILED"

export const INIT_DELETE_CITIES = "INIT_DELETE_CITIES"
export const DELETE_CITIES_SUCCESS = "DELETE_CITIES_SUCCESS"
export const DELETE_CITIES_FAILED = "DELETE_CITIES_FAILED"

export const INIT_SINGLE_CITIES = "INIT_SINGLE_CITIES"
export const SINGLE_CITIES_SUCCESS = "SINGLE_CITIES_SUCCESS"
export const SINGLE_CITIES_FAILED = "SINGLE_CITIES_FAILED"