export const INIT_FETCH_MOVIES = "INIT_FETCH_MOVIES"
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS"
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED"

export const INIT_ADD_MOVIES = "INIT_ADD_MOVIES"
export const ADD_MOVIES_SUCCESS = "ADD_MOVIES_SUCCESS"
export const ADD_MOVIES_FAILED = "ADD_MOVIES_FAILED"

export const INIT_UPDATE_MOVIES = "INIT_UPDATE_MOVIES"
export const UPDATE_MOVIES_SUCCESS = "UPDATE_MOVIES_SUCCESS"
export const UPDATE_MOVIES_FAILED = "UPDATE_MOVIES_FAILED"

export const INIT_DELETE_MOVIES = "INIT_DELETE_MOVIES"
export const DELETE_MOVIES_SUCCESS = "DELETE_MOVIES_SUCCESS"
export const DELETE_MOVIES_FAILED = "DELETE_MOVIES_FAILED"

export const INIT_SINGLE_MOVIES = "INIT_SINGLE_MOVIES"
export const SINGLE_MOVIES_SUCCESS = "SINGLE_MOVIES_SUCCESS"
export const SINGLE_MOVIES_FAILED = "SINGLE_MOVIES_FAILED"